### ISSUE TITLE
CSS de block.ftl

### ISSUE THREAD

**Issue by ghost** [OpenCyLife/ecoweb#3]
J'ai un soucis de mise en page entre la version prototype et mes retouches dans jbake.
Initialement tu as créé le block.ftl pour toutes les parties du site.
Seulement il y a un icone à mettre en page dans la partie "nos actions"
J'ai essayé de mettre le mkdwn en page avec mes limites. Je ne sais pas si on peut aller plus loin.
![1](https://user-images.githubusercontent.com/46707854/67010366-c7b5b300-f0ed-11e9-81a3-5d65528dc690.jpg)
Vs
![2](https://user-images.githubusercontent.com/46707854/67010373-cab0a380-f0ed-11e9-97d9-0becbb5919df.jpg)

**Comment by jderuette** [comment]
Bonjour @flacrabe,

je ne pense pas qu'il soit possible de "jouer" sur le placement des images en MarkDow (et heureusement !). Il faut donc manipuler ces attributs de positionnement en CSS (c'est bien ca :-)). mais il faut pouvoir "identifier" ces images.

Je constate qu'il s'agit d'une énumération d'éléments, je me dit que d'un point de vue sémantique cela serait bien que se soit une liste (non ordonné). En MarkDown, j'ai rajouter un "-" devant chaque item de la liste, et tout le block (titre+image+texte) se retrouve bien dans un bloc LI :-).

Il s'agit d’ailleurs de la version précédente, en revanche le CSS etait cassé à cause d'un ".blockContent" **"**manquant**"**.

J'ai du coup enlever tes images, pour que celle du CSS soient utilisée, tu peux ensuite modifier la taille dans le fichier style-ext.css (taille de l'image et positionnement du texte accompagnement la puce)

Comme on souhaite la **même** images pour chaque je pense qu'il est préférable de ne PAS laissé la main à l'éditeur de contenu sur cet élément.

J'en ai profité pour changer la couleur en noir pour ces "tittre".
