### ISSUE TITLE
questions du lundi

### ISSUE THREAD

**Issue by ghost** [OpenCyLife/ecoweb#5]
Salut, merci pour les derniers déblocages.
quelques questions du lundi :
 - ou se trouve le .ftl pour modifier noue rejoindre ?
- quel est l'inverse de published dans les contents md , j'ai écris unpublished mais je ne sais pas si c'est bonne pratique?
- je ne trouve pas non plus comment ajouter le content des md dans les vignettes poles.(elles sont à jour.
![Annotation 2019-10-21 101028](https://user-images.githubusercontent.com/46707854/67187689-0ba90080-f3eb-11e9-8282-6708fcf1a7db.jpg)

**Comment by jderuette** [comment]
Bonjour frédéric,

"Nous rejoindre" est un des bloc de la Home page, le MarkDown est ici _jBakeSite\content\home_page/rejoindre.md_.

La documentation sur les status de Jbake est disponible ici : https://jbake.org/docs/2.6.4/#status. L'autre valeur prévue est "draft". Dans les ftl je fais souvent un tests "si == published" donc tout autre valeur ignorera le contenu.

Le contenu des pole est ici : jBakeSite\content\poles. Tu peux créer de nouvelle "vignette" en créant un nouveau fichier (de préférence dans ce dossier" avec comme méta donnée : 
```
type=pole
tags=pole
```

Pour le moment, le bloc Home Page affiche juste le titre (cliquable). Ce comportement est dans le fichier templates/index.ftl. Il y a une section spécial pour inclure les pôles : 
`<#if (content.includePoleList)??>`

Je t'ajoute le contenu et un **minimum** de CSS. Je te laisse faire ça beau.

**Comment by jderuette** [comment]
@flacrabe Auras-tu besoin d'aide pour l'image de chaque Pole ? 
As-tu déjà les images ? On (re)passe sur FontAwesome ?

**Comment by ghost** [comment]
Mon soucis est différent pour les pôles:
je voudrais (comme l'ont vu fred et ludovic) afficher le contenu dans la vignette. Et si je ne me trompe pas, ligne 32 environ, on a juste le titre et un lien (block.ftl) qui mène au contenu.

Pour "nous rejoindre" la question" était de tout centrer et de ne pas le coller à gauche comme le reste des "block"

**Comment by jderuette** [comment]
Bonjour @flacrabe,
Pou les contenus des pôles ils sont normalement affiché si tu récupère mes commits (cf : https://github.com/OpenCyLife/ecoweb/commit/741b93133fe44aebc55ffedb1fca948b77da9348#diff-2ecaecd8600ef8ce337476eeaed4dd1dR35).

Pour "nous rejoindre", le contenu est ici : content/home_page/rejoindre.md.
Tu verra en entête un attribut spécifique qui permet de pouvoir définir du CSS spécifique si besoins : 
```specificClass=poleWhite join```
Ici j'ai proposé que ce bloc est une classe CSS "join" (la "poleWhite" est utilisé à plusieurs endroit pour gérer l'alternance de couleur de fond si besoin).

Tu peux aller voir dans ``assets/css/style-ext.css``, tu verras des règles qui impactent ".join". Je n'avais pas inclu ces CSS "specific" dans le block "pôles" sur la page **principale**, je viens de les ajouter.
**Attention** le "centrage" en CSS n'est pas toujours évident a mettre ne place pour que cela fonctionne bien sur tout les navigateurs et reste responsives.

**Comment by ghost** [comment]
on va fermer celle ci
